defaults:
  - template_libero
  - _self_

name: libero_moka_moka
hdf5_path_globs: /data1/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/KITCHEN_SCENE8_put_both_moka_pots_on_the_stove_demo.hdf5
buffer_path: /data1/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/KITCHEN_SCENE8_put_both_moka_pots_on_the_stove_demo.zarr