defaults:
  - template_libero
  - _self_

name: libero_90
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_90/*.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_90/buffer.zarr