defaults:
  - template_libero
  - _self_

name: libero_10
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/*.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/libero_10.zarr