defaults:
  - template_libero
  - _self_

name: libero_stove_moka
hdf5_path_globs: /data1/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/KITCHEN_SCENE3_turn_on_the_stove_and_put_the_moka_pot_on_it_demo.hdf5
buffer_path: /data1/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/KITCHEN_SCENE3_turn_on_the_stove_and_put_the_moka_pot_on_it_demo.zarr