defaults:
  - template_libero
  - _self_

name: libero_mug_mug
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate_demo.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate_demo.zarr