defaults:
  - template_libero
  - _self_

name: libero_cheese_butter
hdf5_path_globs: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/LIVING_ROOM_SCENE2_put_both_the_cream_cheese_box_and_the_butter_in_the_basket_demo.hdf5
buffer_path: /data/shared_workspace/zhangshiqi/dataset/libero/datasets/libero_10/LIVING_ROOM_SCENE2_put_both_the_cream_cheese_box_and_the_butter_in_the_basket_demo.zarr